//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureExtractor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Research\\Data\\Tweets")]
        public string TweetsFilesDirectoryPath {
            get {
                return ((string)(this["TweetsFilesDirectoryPath"]));
            }
            set {
                this["TweetsFilesDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("textFeaturesSingapore")]
        public string TableTextFeatures {
            get {
                return ((string)(this["TableTextFeatures"]));
            }
            set {
                this["TableTextFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Research\\VisualData\\pics1")]
        public string ImagesFilesDirectoryPath {
            get {
                return ((string)(this["ImagesFilesDirectoryPath"]));
            }
            set {
                this["ImagesFilesDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("conceptFeaturesSingapore")]
        public string TableConceptFeatures {
            get {
                return ((string)(this["TableConceptFeatures"]));
            }
            set {
                this["TableConceptFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Research\\Data\\Categories")]
        public string CategoriesFilesDirectoryPath {
            get {
                return ((string)(this["CategoriesFilesDirectoryPath"]));
            }
            set {
                this["CategoriesFilesDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("categoryFeaturesSingapore")]
        public string TableCategoryFeatures {
            get {
                return ((string)(this["TableCategoryFeatures"]));
            }
            set {
                this["TableCategoryFeatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("obesityGroundTruth")]
        public string TableObesityGroundTruth {
            get {
                return ((string)(this["TableObesityGroundTruth"]));
            }
            set {
                this["TableObesityGroundTruth"] = value;
            }
        }
    }
}
